[package]
name = "mdf_runner"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
mdf_schema = { path = "../mdf_schema" }
serde_json = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
