[package]
name = "mdfs_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
mdfs_compiler = { path = "../mdfs_compiler" }
serde_json = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
